language: python

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - export BOTO_CONFIG=/dev/null

install:
  - pip install boto requests urllib3[secure]

script:
  - travis_wait python mrwa2s3.py
