language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - export BOTO_CONFIG=/dev/null

install:
  - pip install -r requirements.txt

script:
  - travis_wait 60 python mrwa2s3.py

# Avoid issues with log truncation
# https://github.com/travis-ci/travis-ci/issues/6018
after_script:
  - sleep 1
